version: "3"

services:
  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/app/
      - "/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt"
    restart: always
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
